Repository grap/grap-odoo-incubator, pull requests merged in 2020-05, with the labels that each got.

#46 12.0 mig web base url force
  web_base_url_force/README.rst
  web_base_url_force/__init__.py
  web_base_url_force/__manifest__.py
  web_base_url_force/__openerp__.py
  web_base_url_force/controllers/__init__.py
  web_base_url_force/controllers/main.py
  web_base_url_force/models/__init__.py
  web_base_url_force/models/ir_config_parameter.py
Labels: bot is merging ⏳

#47 12.0 mig account fiscal position tax included
  account_fiscal_position_tax_included/__init__.py
  account_fiscal_position_tax_included/__manifest__.py
  account_fiscal_position_tax_included/__openerp__.py
  account_fiscal_position_tax_included/demo/account_fiscal_position.xml
  account_fiscal_position_tax_included/demo/account_tax.xml
  account_fiscal_position_tax_included/demo/product_product.xml
  account_fiscal_position_tax_included/demo/res_groups.xml
  account_fiscal_position_tax_included/i18n/fr.po
  account_fiscal_position_tax_included/models/__init__.py
  account_fiscal_position_tax_included/models/account_tax.py
  account_fiscal_position_tax_included/readme/DESCRIPTION.rst
  account_fiscal_position_tax_included/tests/__init__.py
  account_fiscal_position_tax_included/tests/test_module.py
  account_fiscal_position_tax_included/views/view_account_fiscal_position.xml
Labels: bot is merging ⏳

#43 12.0 mig multi search all
  multi_search_abstract/README.rst
  multi_search_abstract/__init__.py
  multi_search_abstract/__manifest__.py
  multi_search_abstract/__openerp__.py
  multi_search_abstract/demo/res_groups.xml
  multi_search_abstract/models/__init__.py
  multi_search_abstract/models/multi_search_mixin.py
  multi_search_abstract/readme/CREDITS.rst
  multi_search_abstract/readme/DESCRIPTION.rst
  multi_search_abstract/static/description/icon.png
  multi_search_abstract/views/view_base_config_settings.xml
  multi_search_abstract/views/view_res_config_settings.xml
  multi_search_partner/__init__.py
  multi_search_partner/__manifest__.py
  multi_search_partner/__openerp__.py
  multi_search_partner/models/__init__.py
  multi_search_partner/models/base_config_settings.py
  multi_search_partner/models/res_config_settings.py
  multi_search_partner/models/res_partner.py
  multi_search_partner/readme/CONFIGURE.rst
  multi_search_partner/readme/USAGE.rst
  multi_search_partner/static/description/partner_search.png
  multi_search_partner/static/description/setting_form.png
  multi_search_partner/tests/__init__.py
  multi_search_partner/tests/test_module.py
  multi_search_partner/views/view_base_config_settings.xml
  multi_search_partner/views/view_res_config_settings.xml
  multi_search_product/__init__.py
  multi_search_product/__manifest__.py
  multi_search_product/__openerp__.py
  multi_search_product/models/__init__.py
  multi_search_product/models/base_config_settings.py
  multi_search_product/models/product_product.py
  multi_search_product/models/product_template.py
  multi_search_product/models/res_config_settings.py
  multi_search_product/readme/CONFIGURE.rst
  multi_search_product/readme/USAGE.rst
  multi_search_product/static/description/product_search.png
  multi_search_product/static/description/setting_form.png
  multi_search_product/tests/__init__.py
  multi_search_product/tests/test_module.py
  multi_search_product/views/view_base_config_settings.xml
  multi_search_product/views/view_res_config_settings.xml
Labels: bot is merging ⏳

#48 [12.0][MIG] product print category
  product_print_category/README.rst
  product_print_category/__init__.py
  product_print_category/__manifest__.py
  product_print_category/__openerp__.py
  product_print_category/data/report_paperformat.xml
  product_print_category/demo/product_print_category.xml
  product_print_category/demo/product_product.xml
  product_print_category/demo/qweb_template.xml
  product_print_category/demo/res_groups.xml
  product_print_category/i18n/fr.po
  product_print_category/migrations/12.0.1.0.0/pre-migration.py
  product_print_category/models/__init__.py
  product_print_category/models/product_print_category.py
  product_print_category/models/product_product.py
  product_print_category/models/product_template.py
  product_print_category/models/res_company.py
  product_print_category/readme/CONTRIBUTORS.rst
  product_print_category/readme/DESCRIPTION.rst
  product_print_category/readme/ROADMAP.rst
  product_print_category/readme/USAGE.rst
  product_print_category/report/__init__.py
  product_print_category/report/ir_actions_report.xml
  product_print_category/report/report_pricetag.py
  product_print_category/report/report_pricetag.xml
  product_print_category/security/ir_module_category.xml
  product_print_category/security/res_groups.xml
  product_print_category/static/description/index.html
  product_print_category/static/description/print_category.png
  product_print_category/static/description/print_products.png
  product_print_category/static/description/product_print_options.png
  product_print_category/tests/__init__.py
  product_print_category/tests/test_product_print_category.py
  product_print_category/views/action.xml
  product_print_category/views/menu.xml
  product_print_category/views/view_product_print_category.xml
  product_print_category/views/view_product_product.xml
  product_print_category/views/view_product_template.xml
  product_print_category/views/view_res_company.xml
  product_print_category/wizard/__init__.py
  product_print_category/wizard/product_print_wizard.py
  product_print_category/wizard/product_print_wizard_line.py
  product_print_category/wizard/view_product_print_wizard.xml
Labels: bot is merging ⏳

#33 [12.0][MIG] Base legal info
  base_company_legal_info/README.rst
  base_company_legal_info/__init__.py
  base_company_legal_info/__manifest__.py
  base_company_legal_info/demo/res_company.xml
  base_company_legal_info/demo/res_groups.xml
  base_company_legal_info/i18n/fr.po
  base_company_legal_info/models/__init__.py
  base_company_legal_info/models/res_company.py
  base_company_legal_info/readme/CONFIGURE.rst
  base_company_legal_info/readme/CONTRIBUTORS.rst
  base_company_legal_info/readme/DESCRIPTION.rst
  base_company_legal_info/static/description/index.html
  base_company_legal_info/static/description/report_layout_footer.png
  base_company_legal_info/static/description/res_company_form.png
  base_company_legal_info/views/external_layout_footer.xml
  base_company_legal_info/views/view_res_company.xml
Labels: Ready to Merge, approved, bot is merging ⏳

#35 [12.0][MIG] Product category product qty
  product_category_product_qty/README.rst
  product_category_product_qty/__init__.py
  product_category_product_qty/__manifest__.py
  product_category_product_qty/demo/res_groups.xml
  product_category_product_qty/l10n/fr.po
  product_category_product_qty/models/__init__.py
  product_category_product_qty/models/product_category.py
  product_category_product_qty/static/description/index.html
  product_category_product_qty/static/description/product_category_form.png
  product_category_product_qty/static/description/product_category_tree.png
  product_category_product_qty/views/view_product_category.xml
Labels: approved, bot is merging ⏳

#39 [MIG][12.0] stock_inventory_merge
  stock_inventory_merge/README.rst
  stock_inventory_merge/__init__.py
  stock_inventory_merge/__manifest__.py
  stock_inventory_merge/__openerp__.py
  stock_inventory_merge/demo/product_product.xml
  stock_inventory_merge/demo/res_groups.xml
  stock_inventory_merge/demo/stock_inventory.xml
  stock_inventory_merge/i18n/fr.po
  stock_inventory_merge/models/__init__.py
  stock_inventory_merge/models/stock_inventory.py
  stock_inventory_merge/models/stock_inventory_line.py
  stock_inventory_merge/models/wizard_stock_inventory_merge.py
  stock_inventory_merge/static/description/index.html
  stock_inventory_merge/tests/__init__.py
  stock_inventory_merge/tests/test_module.py
  stock_inventory_merge/tests/test_stock_inventory_merge.py
  stock_inventory_merge/views/view_stock_inventory.xml
  stock_inventory_merge/views/view_stock_inventory_line.xml
  stock_inventory_merge/views/view_wizard_stock_inventory_merge.xml
Labels: bot is merging ⏳

#28 [12.0][MIG] - pos_sector
  pos_sector/__init__.py
  pos_sector/__manifest__.py
  pos_sector/demo/pos_config.xml
  pos_sector/demo/pos_sector.xml
  pos_sector/demo/product_product.xml
  pos_sector/demo/res_groups.xml
  pos_sector/models/__init__.py
  pos_sector/models/pos_config.py
  pos_sector/models/pos_sector.py
  pos_sector/models/product_template.py
  pos_sector/readme/DESCRIPTION.rst
  pos_sector/security/ir_rule.xml
  pos_sector/security/res_groups.xml
  pos_sector/static/description/pos_config_form.png
  pos_sector/static/description/pos_sector_tree.png
  pos_sector/static/description/product_form.png
  pos_sector/static/src/js/models.js
  pos_sector/views/action.xml
  pos_sector/views/assets.xml
  pos_sector/views/menu.xml
  pos_sector/views/view_pos_config.xml
  pos_sector/views/view_pos_sector.xml
  pos_sector/views/view_product_template.xml
Labels: bot is merging ⏳

#34 [12.0][MIG] Duplication Account Invoice
  duplication_account_invoice/__init__.py
  duplication_account_invoice/__manifest__.py
  duplication_account_invoice/i18n/fr.po
  duplication_account_invoice/models/__init__.py
  duplication_account_invoice/models/account_invoice_duplication_wizard.py
  duplication_account_invoice/models/account_invoice_duplication_wizard_date_line.py
  duplication_account_invoice/tests/__init__.py
  duplication_account_invoice/tests/test_duplication_account_invoice.py
  duplication_account_invoice/views/action.xml
  duplication_account_invoice/views/view_account_invoice_duplication_wizard.xml
Labels: bot is merging ⏳

#37 12.0 mig product simple pricelist
  product_simple_pricelist/__init__.py
  product_simple_pricelist/__manifest__.py
  product_simple_pricelist/demo/product_pricelist.xml
  product_simple_pricelist/demo/res_groups.xml
  product_simple_pricelist/i18n/fr.po
  product_simple_pricelist/models/__init__.py
  product_simple_pricelist/models/product_pricelist.py
  product_simple_pricelist/models/product_product.py
  product_simple_pricelist/models/product_simple_pricelist_item.py
  product_simple_pricelist/models/product_simple_pricelist_item_update_wizard.py
  product_simple_pricelist/readme/CONFIGURE.rst
  product_simple_pricelist/readme/ROADMAP.rst
  product_simple_pricelist/security/ir.model.access.csv
  product_simple_pricelist/security/ir_rule.xml
  product_simple_pricelist/static/description/pricelist_item_form.png
  product_simple_pricelist/static/description/product_pricelist_tree.png
  product_simple_pricelist/static/description/product_product_tree.png
  product_simple_pricelist/static/description/simple_price_list_item.png
  product_simple_pricelist/static/description/wizard_form.png
  product_simple_pricelist/tests/__init__.py
  product_simple_pricelist/tests/test_product_simple_pricelist.py
  product_simple_pricelist/views/action.xml
  product_simple_pricelist/views/view_product_pricelist.xml
  product_simple_pricelist/views/view_product_product.xml
  product_simple_pricelist/views/view_product_simple_pricelist_item.xml
  product_simple_pricelist/views/view_product_simple_pricelist_item_update_wizard.xml
Labels: bot is merging ⏳

#38 [12.0][MIG] Stock internal use of products
  stock_internal_use_of_products/README.rst
  stock_internal_use_of_products/__init__.py
  stock_internal_use_of_products/__manifest__.py
  stock_internal_use_of_products/data/ir_sequence.xml
  stock_internal_use_of_products/demo/account_account.xml
  stock_internal_use_of_products/demo/account_journal.xml
  stock_internal_use_of_products/demo/account_tax.xml
  stock_internal_use_of_products/demo/account_tax_code.xml
  stock_internal_use_of_products/demo/internal_use.xml
  stock_internal_use_of_products/demo/internal_use_case.xml
  stock_internal_use_of_products/demo/product_product.xml
  stock_internal_use_of_products/demo/res_groups.xml
  stock_internal_use_of_products/i18n/fr.po
  stock_internal_use_of_products/migrations/8.0.2.0.0/pre-migration.py
  stock_internal_use_of_products/models/__init__.py
  stock_internal_use_of_products/models/internal_use.py
  stock_internal_use_of_products/models/internal_use_case.py
  stock_internal_use_of_products/models/internal_use_line.py
  stock_internal_use_of_products/models/internal_use_mass_generate_wizard.py
  stock_internal_use_of_products/models/product_product.py
  stock_internal_use_of_products/models/stock_move.py
  stock_internal_use_of_products/readme/CONTRIBUTORS.rst
  stock_internal_use_of_products/security/ir_rule.xml
  stock_internal_use_of_products/static/description/index.html
  stock_internal_use_of_products/tests/__init__.py
  stock_internal_use_of_products/tests/test_stock_internal_use_of_products.py
  stock_internal_use_of_products/views/action.xml
  stock_internal_use_of_products/views/menu.xml
  stock_internal_use_of_products/views/templates.xml
  stock_internal_use_of_products/views/view_internal_use.xml
  stock_internal_use_of_products/views/view_internal_use_case.xml
  stock_internal_use_of_products/views/view_internal_use_mass_generate_wizard.xml
Labels: bot is merging ⏳

#60 [FIX] stock_internal_use_of_products : remove obsolete migration script
  stock_internal_use_of_products/migrations/8.0.2.0.0/pre-migration.py
Labels: bot is merging ⏳
